Models/DoNotInsure.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ucon.Models
{
    public class DoNotInsure
    {
		    public bool onceInTable { set; get; }
	        public string make { set; get; }
	        public string model { set; get; }
	        public string model_type { set; get; }
	        public string extension { set; get; }
	        public int year { set; get; }
            public bool success { set; get; }
            public bool do_not_insure { set; get; }
    }
       
}

Controllers/DoNotInsureController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ucon.Models;

namespace Ucon.Controllers
{
    public class DoNotInsureController : Controller
    {
        // GET: DoNotInsure
        public ActionResult Index()
        {
            DoNotInsure DontInsure = new DoNotInsure();
            return View(DontInsure);
        }


        [HttpPost]
        public ActionResult Index(DoNotInsure DontInsure)
        {
            string UnderWriterResponse = KeyManagement.PerformRequest("epic_mwVehDoNotInsure",
            KeyManagement.RequestType.Parameter, "All", DontInsure);
            JObject MyResponse = JObject.Parse(UnderWriterResponse);

            if (MyResponse["do_not_insure"] != null)
            {
                DontInsure.do_not_insure = (bool)(MyResponse["do_not_insure"]);
                DontInsure.success = (bool)(MyResponse["success"]);
            }

            return RedirectToAction("IndexResult", DontInsure);

       }

        public ActionResult IndexResult(DoNotInsure DontInsure)
        {
            return View(DontInsure);
        }

    }
}

Views/DoNotInsure/Index.cshtml
@model Ucon.Models.DoNotInsure


@using (Html.BeginForm())

{
    @Html.AntiForgeryToken()
    <div class="container">
        <h1 class="text-center" style="color:#13a89e;font-weight:bold; font-family:Cambria"><span class="glyphicon glyphicon-remove"></span>Vehicle Exception</h1>
        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.onceInTable, "Once Exist In Table", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.onceInTable)
                        @Html.ValidationMessageFor(model => model.onceInTable, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.make, "Make", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.make, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.make, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.model, "Model", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.model, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.model, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.model_type, "Model Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.model_type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.model_type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.extension, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.extension, "Extensions", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.extension, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.year, "Year", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.year, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.year, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Check Status" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<hr />



<div class="well">
    <table>
        <tr>
            <td><h1><span class="glyphicon glyphicon-info-sign"></span></h1></td>
            <td>
                <p>
                    This method does a search on the vehicle exception table for the vehicle passed to it and indicates if it should be insured.
                </p>
            </td>
        </tr>
    </table>

</div>

<h4>Resources</h4>
<div class="well">
    <i>Method Name</i>
    <h5 style="color:#13a89e;font-weight:bold; font-family:Cambria"><span class="glyphicon glyphicon-flash"></span>epic_mwVehDoNotInsure</h5>

</div>

<div class="well">
    <i>Json Request Body</i>
    <p>
        {"resquestkey" : {"key" : "10740677-b2ca-409d-9844-c2bf9f5ca467"},
        "parameter" : {
        "onceInTable" : false,
        "make" : "",
        "model" : "",
        "model_type" : "",
        "extension" : "",
        "year" : 0
        }}
    </p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/DoNotInsure/IndexResult.cshtml
@model Ucon.Models.DoNotInsure

<div>
    
    <hr />

    <h1 class="text-center" style="color:#13a89e;font-weight:bold; font-family:Cambria"><span class="glyphicon glyphicon-remove"></span>Vehicle Exception</h1>

    <div class="well">
        <table>
            <tr>
                <td><h1><span class="glyphicon glyphicon-info-sign"></span></h1></td>
                <td>
                    <p>
                        This method does a search on the vehicle exception table for the vehicle passed to it and indicates if it should be insured.
                    </p>
                </td>
            </tr>
        </table>

    </div>

    <h4>Resources</h4>
    <div class="well">
        <i>Method Name</i>
        <h5 style="color:#13a89e;font-weight:bold; font-family:Cambria"><span class="glyphicon glyphicon-flash"></span>epic_mwVehDoNotInsure</h5>

    </div>

    <div class="well">
        <i>Json Request Body</i>
        <p>
            {"resquestkey" : {"key" : "10740677-b2ca-409d-9844-c2bf9f5ca467"},
            "parameter" : {
            "onceInTable" : false,
            "make" : "",
            "model" : "",
            "model_type" : "",
            "extension" : "",
            "year" : 0
            }}
        </p>
    </div>

    <hr />

    <div class="well">
        <dl class="dl-horizontal">
            <dt>
                Once Exist In Table
            </dt>

            <dd>
                @Html.DisplayFor(model => model.onceInTable)
            </dd>

            <dt>
                Make
            </dt>

            <dd>
                @Html.DisplayFor(model => model.make)
            </dd>

            <dt>
                Model
            </dt>

            <dd>
                @Html.DisplayFor(model => model.model)
            </dd>

            <dt>
                Model Type
            </dt>

            <dd>
                @Html.DisplayFor(model => model.model_type)
            </dd>

            <dt>
                Extension
            </dt>

            <dd>
                @Html.DisplayFor(model => model.extension)
            </dd>

            <dt>
                Year
            </dt>

            <dd>
                @Html.DisplayFor(model => model.year)
            </dd>

            <dt>
                Insurable
            </dt>

            <dd>
                @Html.DisplayFor(model => model.do_not_insure)
            </dd>

        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Index", "DoNotInsure")
    </div>
</div>